# %% [markdown]
# # 04 · Nonstationary flood frequency at Brays Bayou
#
# These seven LP-III structures use the same observed metric flood record.
# Their location, scale and skew trends are explicit model choices. The eighth
# case averages only three selected fits using fresh DIC weights.
# Restart Kernel and Run All builds and estimates each model through BestFit.

# %%
from pathlib import Path
import sys
ROOT = Path.cwd() if (Path.cwd() / "runtime-lock.json").exists() else Path.cwd().parent
sys.path.insert(0, str(ROOT))
from time import perf_counter
from math import exp
import pandas as pd
from IPython.display import display
from bestfit_examples.runtime import load_bestfit
from bestfit_examples.raw import load_raw
from bestfit_examples.fresh import plot_context, plots, show, record_run
runtime = load_bestfit()
print(runtime)
from System import Array, Double, DateTime
from System.Collections.Generic import List
from Numerics.Data import ProbabilityOrdinates
from Numerics.Data.Statistics import Probability
from Numerics.Distributions import UnivariateDistributionType
from RMC.BestFit.Models import DataFrame, ExactData, ExactSeries, IntervalData, ThresholdData, UnivariateDistribution
from RMC.BestFit.Models.TrendFunctions.Support import TrendModelType
from RMC.BestFit.Analyses import (UnivariateAnalysis, CompositeAnalysis,
                                  WeightedUnivariateAnalysis, CompositeType, AverageMethod)
from RMC.BestFit.Estimation import BayesianAnalysis

# %% [markdown]
# ## Brays Bayou's observed record
#
# Keep the metric series and source threshold window. The long raw USGS text is
# provenance; model observations come from the decoded exact and threshold rows.

# %%
raw = load_raw("nsffa-brays-bayou-texas")
input_name = "USGS 08075000 Brays Bayou - Metric"
observed = raw["inputs"][input_name]
frame = DataFrame()
frame.ExactSeries = ExactSeries()
for row in observed["series"]["ExactSeries"]:
    point = ExactData(DateTime.Parse(row["DateTime"]), float(row["Value"]))
    point.Index = int(row["Index"])
    point.IsLowOutlier = row.get("IsLowOutlier", "False") == "True"
    frame.ExactSeries.Add(point)
for row in observed["series"]["IntervalSeries"]:
    frame.IntervalSeries.Add(IntervalData(int(row["Index"]), float(row["LowerValue"]),
                                          float(row["Value"]), float(row["UpperValue"])))
for row in observed["series"]["ThresholdSeries"]:
    threshold = ThresholdData(int(row["StartIndex"]), int(row["EndIndex"]), float(row["Value"]))
    threshold.NumberAbove = int(row["NumberAbove"])
    frame.ThresholdSeries.Add(threshold)
frame.PlottingParameter = float(observed["attributes"]["PlottingParameter"])
frame.CalculatePlottingPositions()
display(pd.DataFrame(observed["series"]["ExactSeries"]).head())
print({"exact": frame.ExactSeries.Count, "threshold windows": frame.ThresholdSeries.Count})

# %% [markdown]
# ## Seven explicit trend structures
#
# LP-III trend coordinates are mean of log, standard deviation of log, then
# skew of log. All source trends begin in 1929 and are evaluated at 2024.
# The bounds and uniform priors are generated by BestFit's SetTrendModel from
# these same observations; they are inspected below before estimation.

# %%
trend_specs = [
    ("NSFFA - Constant", "Constant", "Constant", "Constant"),
    ("NSFFA - Linear", "Linear", "Constant", "Constant"),
    ("NSFFA - Logistic", "Logistic", "Constant", "Constant"),
    ("NSFFA - Step", "StepFunction", "Constant", "Constant"),
    ("NSFFA - Linear - Logistic", "Linear", "Logistic", "Constant"),
    ("NSFFA - Logistic - Logistic", "Logistic", "Logistic", "Constant"),
    ("NSFFA - Step - Logistic", "StepFunction", "Logistic", "Constant"),
]
mcmc_design = {
    "NSFFA - Constant": (6, 30, 300, .971630931303994, 10000),
    "NSFFA - Linear": (8, 40, 400, .8414570696119914, 10000),
    "NSFFA - Logistic": (8, 40, 400, .8414570696119914, 10000),
    "NSFFA - Step": (10, 50, 500, .7526220831200742, 10000),
    "NSFFA - Linear - Logistic": (10, 50, 500, .7526220831200742, 10000),
    "NSFFA - Logistic - Logistic": (10, 50, 500, .7526220831200742, 20000),
    "NSFFA - Step - Logistic": (12, 60, 600, .6870468203356547, 10000),
}
aep = [1e-6, 2e-6, 5e-6, 1e-5, 2e-5, 5e-5, .0001, .0002, .0005,
       .001, .002, .005, .01, .02, .05, .1, .2, .3, .5, .7, .8, .9, .95, .98, .99]
analyses, models, timings = {}, {}, {}
for name, mean_trend, scale_trend, skew_trend in trend_specs:
    chains, thinning, initial, jump, output_length = mcmc_design[name]
    model = UnivariateDistribution(frame, UnivariateDistributionType.LogPearsonTypeIII)
    model.UseDefaultFlatPriors = True
    model.UseJeffreysRuleForScale = True
    model.IsNonstationary = True
    model.SetTrendModel(0, getattr(TrendModelType, mean_trend))
    model.SetTrendModel(1, getattr(TrendModelType, scale_trend))
    model.SetTrendModel(2, getattr(TrendModelType, skew_trend))
    model.ParameterTimeIndex = 2024
    model.Alpha = .5
    for trend in model.TrendModels:
        trend.StartIndex = 1929
    analysis = UnivariateAnalysis(model)
    analysis.ProbabilityOrdinates = ProbabilityOrdinates(Array[Double](aep))
    bayes = analysis.BayesianAnalysis
    bayes.UseSimulationDefaults = True
    bayes.Type = BayesianAnalysis.SamplerType.DEMCzs
    bayes.NumberOfChains = chains
    bayes.ThinningInterval = thinning
    bayes.WarmupIterations = 1750
    bayes.Iterations = 3500
    bayes.PRNGSeed = 12345
    bayes.UseAdvancedSimulationDefaults = True
    bayes.InitialIterations = initial
    bayes.Jump = jump
    bayes.JumpThreshold = .1
    bayes.SnookerThreshold = .1
    bayes.Noise = 1e-12
    bayes.Scale = 5.6644
    bayes.Beta = .05
    bayes.MaxTreeDepth = 10
    bayes.CredibleIntervalWidth = .9
    bayes.OutputLength = output_length
    bayes.PointEstimator = BayesianAnalysis.PointEstimateType.PosteriorMean
    started = perf_counter()
    analysis.RunAsync(None).GetAwaiter().GetResult()
    timings[name] = perf_counter() - started
    analyses[name], models[name] = analysis, model
    record_run(name, analysis, timings[name], raw=raw, model=model)

# %% [markdown]
# ## Compare the fitted structures at 2024
#
# A changing return level must be interpreted at its specified year. The
# chronology is a separate computed output, not a timeless frequency curve.

# %%
rows = []
for name, mean_trend, scale_trend, skew_trend in trend_specs:
    model, analysis = models[name], analyses[name]
    rows.append({"Case": name, "Location trend": mean_trend, "Scale trend": scale_trend,
                 "Skew trend": skew_trend, "Year": model.ParameterTimeIndex,
                 "DIC": float(analysis.BayesianAnalysis.DIC),
                 "1% AEP parameter point estimate": float(analysis.AnalysisResults.ModeCurve[aep.index(.01)])})
display(pd.DataFrame(rows))
diagnostics = []
for name, *_ in trend_specs:
    result = analyses[name].BayesianAnalysis.Results
    for i, parameter in enumerate(result.ParameterResults):
        stats = parameter.SummaryStatistics
        diagnostics.append({"Case": name, "Parameter index": i,
                            "R-hat": float(stats.Rhat), "ESS": float(stats.ESS)})
display(pd.DataFrame(diagnostics))
display(pd.DataFrame([
    {"Trend": str(trend.Type), "Coefficient": str(parameter.Name),
     "Lower": float(parameter.LowerBound), "Upper": float(parameter.UpperBound)}
    for trend in models["NSFFA - Step - Logistic"].TrendModels for parameter in trend.Parameters]))

# %% [markdown]
# ## DIC-weighted model average
#
# This composite uses only the three saved child names below. Its weights come
# from their freshly computed DIC values; it has no independent MCMC chain.

# %%
selected_names = ["NSFFA - Linear - Logistic", "NSFFA - Logistic - Logistic",
                  "NSFFA - Step - Logistic"]
children = List[WeightedUnivariateAnalysis]()
for name in selected_names:
    children.Add(WeightedUnivariateAnalysis(analyses[name], 1.0 / 3.0))
average = CompositeAnalysis(children)
average.CompositeDistributionType = CompositeType.ModelAverage
average.ModelAverageMethod = AverageMethod.DIC
average.Dependency = Probability.DependencyType.Independent
average.IsMaximum = True
average.ProbabilityOrdinates = ProbabilityOrdinates(Array[Double](aep))
average.BayesianAnalysis.PRNGSeed = 12345
average.BayesianAnalysis.OutputLength = 10000
average.BayesianAnalysis.CredibleIntervalWidth = .9
average.EstimateModelWeights()
assert abs(sum(float(item.Weight) for item in average.Analyses) - 1.0) < 1e-10
child_dic = [float(analyses[name].BayesianAnalysis.DIC) for name in selected_names]
relative_scores = [exp(-.5 * (score - min(child_dic))) for score in child_dic]
independent_weights = [score / sum(relative_scores) for score in relative_scores]
for item, expected in zip(average.Analyses, independent_weights):
    assert abs(float(item.Weight) - expected) < 1e-12
started = perf_counter()
average.RunAsync(None).GetAwaiter().GetResult()
timings["Bayesian Model Average"] = perf_counter() - started
analyses["Bayesian Model Average"] = average
record_run("Bayesian Model Average", average, timings["Bayesian Model Average"], raw=raw)
display(pd.DataFrame([{"Child": name, "Fresh DIC weight": float(average.Analyses[i].Weight)}
                      for i, name in enumerate(selected_names)]))

# %% [markdown]
# ## Visualize fresh conditional curves and chronology
#
# Higher model flexibility does not identify a causal driver. The average covers
# only the selected three structures and their fitted weights.

# %%
specs, contexts = {}, {}
for name, _, _, _ in trend_specs:
    context = plot_context(analyses[name], models[name], name=name, raw=raw,
                           frame=frame, metadata=observed["metadata"])
    contexts[name] = context
    specs[name] = plots(context)
    show(specs[name]["frequency"])
    if "chronology" in specs[name]:
        show(specs[name]["chronology"])
average_context = plot_context(average, name="Bayesian Model Average", raw=raw, frame=frame,
                               metadata=observed["metadata"],
                               dependencies={name: contexts[name] for name in selected_names})
specs["Bayesian Model Average"] = plots(average_context)
show(specs["Bayesian Model Average"]["frequency"])

# %% [markdown]
# **Adapt this example:** retain observed dates and threshold context, then
# choose and disclose trend forms, evaluation year and model-average membership.
